excluded:
  - '**/Pods'
  - '**/node_modules'
  - '**/__tests__'
  # packages/react-native-otlp copied/pasted files from opentelemetry-swift
  - '**/InternalOpenTelemetry'
  
disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - function_parameter_count
  - notification_center_detachment
  - compiler_protocol_init
  - type_body_length # it doesn't support auto-correction, disabling now
  - todo # it doesn't support auto-correction, disabling now
  - file_length # it doesn't support auto-correction, disabling now

opt_in_rules:
  - conditional_returns_on_newline

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)

line_length:
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_function_declarations: true
  ignores_urls: true
  warning: 230
  error: 250

# TODO: need to discuss about this rule
# file_length:
#   warning: 800
#   error: 1000

type_name:
  max_length:
    warning: 60
  allowed_symbols: ["_"]

function_body_length:
  warning: 100
  error: 300

large_tuple:
  warning: 4
  error: 6

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 20
  error: 30
