name: Foo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: dorny/paths-filter@v2
        id: changed_files
        with:
          list-files: json
          filters: |
            txt:
            - '**/*.txt'
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: corepack enable
      - run: yarn
      - run: yarn run foo
      - run: echo ${{ steps.changed_files.outputs.txt_files }}
